### ISSUE TITLE
Non-Admin Users Unable to Schedule Draft Publish Date

### ISSUE THREAD

**Issue by Decyphr** [neustadt-swiss/craft-publisher#1]
I'm trying to give a user group access to schedule draft publishing, but can't seem to find any permissions related to this plugin in the Craft control panel. Is there something I'm missing, or a specific default permission that users need to have access to in order to schedule drafts? 

I've verified that the plugin is installed and running correctly and that I can schedule drafts as an Admin user. 

Any help is greatly appreciated. Thanks!

**Comment by Decyphr** [comment]
Was able to identify the issue. In Craft 4 the "publishEntries" user permission has been renamed "saveEntries".

Simply updating the following two files in the plugin's vendor folder seems to resolve the issue:

```twig
{# ../goldinteractive/craft-publisher/src/templates/_cp/entriesEditRightPane.twig #}

{# change this ❌ #}
{% set canPublishDraft = currentUser.can('publishEntries'~permissionSuffix) %}

{# to this ✅ #}
{% set canPublishDraft = currentUser.can('saveEntries'~permissionSuffix) %}
```

```php
// ../goldinteractive/craft-publisher/src/controllers/EntriesController.php

{# change this ❌ #}
 if ($draft->enabled) {
    $this->requirePermission('publishEntries:'.$entry->section->uid);
}

{# to this ✅ #}
if ($draft->enabled) {
    $this->requirePermission('saveEntries:'.$entry->section->uid);
}
```

**Comment by lukasNo1** [comment]
Thanks for reporting this. I just created a new release 3.0.1 with the fix.
