### ISSUE TITLE
Incapable of scrolling and setting the post's date on a schedule.

### ISSUE THREAD

**Issue by thangaraj-moorthi** [neustadt-swiss/craft-publisher#2]
Hello craft-publisher,

- We appreciate your wonderful plugin. We've acquired your plugin for Craft version 4, and we are currently experiencing a bug on our website.
- Specifically, we are encountering issues when trying to schedule a date at the end of the page. Unfortunately, we cannot scroll to the end of the page due to certain CSS restrictions related to the "top" property.

![image](https://github.com/Goldinteractive/craft-publisher/assets/41003343/594e777d-79a0-4ee2-8928-48ec97d7fd5e)
- Additionally, we are unable to scroll separately within the "details-container" and "content-container".
- **Please take note**: The content within the "content-container" exceeds that of the "details-container," allowing us to scroll and access the schedule section.

- Could you kindly address and rectify this bug, and then release an updated version? Our clients have a keen interest in utilizing the scheduling feature provided by your plugin, as it significantly saves us time.

Please don't hesitate to reach out if you have any questions or require further information.

Thank you in advance.

**Comment by lukasNo1** [comment]
Hey @thangaraj-fuint this seems like a craft cms bug, version 4.5.5 fixed a css bug which could be your issue
https://github.com/craftcms/cms/blob/develop/CHANGELOG.md#455---2023-09-14

"Fixed a bug where page sidebars and detail panes weren’t scrolling properly if their height was greater than the main content pane height."

So after a craft update this should be fixed

**Comment by thangaraj-moorthi** [comment]
Hi @lukasNo1 

Indeed, it's a bug on the Craft side of things.
We're actively addressing it.
Appreciate your prompt response.
