### ISSUE TITLE
Craft 5 support

### ISSUE THREAD

**Issue by mtwalsh** [neustadt-swiss/craft-publisher#3]
Hi,

Are there any plans to upgrade this plugin for Craft 5?

**Comment by lukasNo1** [comment]
Yes, we don't have any resources for the next 4 weeks, but I want to do the craft 5 update here soon

**Comment by mtwalsh** [comment]
Thanks for the response, that's good to know.

**Comment by lukasNo1** [comment]
hey @mtwalsh 

I just created a new release 4.0.0 with the craft 5 support. Everything still seems to work the same.
If you find any errors, please let me know!

**Comment by mtwalsh** [comment]
Amazing, thank you @lukasNo1! We don't yet have the go ahead on our project that we were planning to us this on but it's good to know the plugin is now available.
